### ISSUE TITLE
Improve the betfin stats page

### ISSUE THREAD

**Issue by bf-monster** [betfinio/staking#26]
- [x] STATS 1: Total members, total stakers, total players
- [x] Charts displaying payouts from staking in particular cycles as bars. Those should be separate charts for dynamic staking.
- [x] Chart comparing conservative and dynamic staking earnings in the defined timeframe
- [x]  STATS 2: Total staked, total earnings, affiliate paid
- [x] Update the total staked and total stakers charts. 
- [x] Free circ bet, 30D volume, Liquidity in uniswap
- [x] 2 pie charts comparing the tokenomy and and curent BET distribution. It is important to emphasize the tokens in circulation (free, staked, in liquidity pool) and tokens that are completely locked.

_

**Comment by bf-monster** [comment]
https://thegraph.com/docs/en/developing/creating-a-subgraph/#timeseries-and-aggregations

**Comment by bf-monster** [comment]
https://nivo.rocks/bar/

**Comment by BF-MAGNUM** [comment]
![Image](https://github.com/user-attachments/assets/badea22b-d303-4bf6-9c79-0e24bbd34ee6)
Hello guys, I send you a small proposal how should it look like. 

I am sorry for confusion but I would like to amend the specs after some visualization. I believe it is all clear. As attached.

**Comment by bf-san** [comment]
https://github.com/graphprotocol/common-subgraphs/tree/main/aggregation-example
