### ISSUE TITLE
display stones in staking statistics

### ISSUE THREAD

**Issue by bf-monster** [betfinio/staking#65]

**Comment by bf-monster** [comment]
![Image](https://github.com/user-attachments/assets/1070bede-393c-46a5-b359-701b5b3165b4)

**Comment by bf-tom** [comment]
@bf-monster 11.73B seems to be too much, isnt it Millions?

 ![Image](https://github.com/user-attachments/assets/479385e8-b539-40f0-bec8-f83af8c38779)

**Comment by bf-tom** [comment]
probably not real data right.. ignore my previous comment pls
